apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-deployment
  template:
    metadata:
      labels:
        app: go-deployment
    spec:
      containers:
      - name: go
        image: container-apps-health-probe-examples-go:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /probe/http
            port: 3000
            httpHeaders:
            - name: probe
              value: "Liveness"
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /probe/https
            port: 3443
            scheme: HTTPS
            httpHeaders:
            - name: probe
              value: "Readiness"
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /probe/http
            port: 3000
            httpHeaders:
            - name: probe
              value: "Startup"
          periodSeconds: 10
          initialDelaySeconds: 5
