apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-deployment
  template:
    metadata:
      labels:
        app: java-deployment
    spec:
      containers:
      - name: java
        image: container-apps-health-probe-examples-java:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /probe/http
            port: 8080
            httpHeaders:
            - name: probe
              value: "Liveness"
          periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /probe/https
              port: 8443
              scheme: HTTPS
              httpHeaders:
              - name: probe
                value: "Readiness"
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /probe/http
              port: 8080
              httpHeaders:
              - name: probe
                value: "Startup"
            periodSeconds: 10
            initialDelaySeconds: 5