apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-deployment
  template:
    metadata:
      labels:
        app: node-deployment
    spec:
      containers:
      - name: node
        image: container-apps-health-probe-examples-node:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /probe/http
            port: 3000
            httpHeaders:
            - name: probe
              value: "Liveness"
        readinessProbe:
          httpGet:
            path: /probe/https
            port: 8443
            httpHeaders:
            - name: probe
              value: "Readiness"
        startupProbe:
          httpGet:
            path: /probe/http
            port: 3000
            httpHeaders:
            - name: probe
              value: "Startup"